Testcase: sort-project-filter-scan
nothing-new-labs/cso-demo pull request #14
Opened 2023-09-27 14:10 UTC by linbo-lin

2023-09-28 13:57 UTC, davidli2010 requested changes

2023-09-28 13:57 UTC, davidli2010 commented on src/task/apply_rule.rs
> +                let required_prop = optimizer_ctx.required_properties();
`optimizer_ctx.required_properties()` is the top required properties for root group, here we should use the required properties for current group.

2023-09-28 13:57 UTC, davidli2010 commented on src/rule/mod.rs
> +        // todo
remove `todo`

2023-09-28 13:57 UTC, davidli2010 commented on tests/opt.rs
> +fn temp() {
give this test case a reasonable name

2023-09-28 13:57 UTC, davidli2010 commented on tests/opt.rs
> +    dbg!(physical_plan);
check the result is expected through `assert!`

2023-10-08 04:05 UTC, LiBinfeng-01 approved these changes

2023-10-08 04:06 UTC, merged