Metadata
nothing-new-labs/cso-demo pull request #4
Opened 2023-07-29 14:12 UTC by linbo-lin

2023-08-06 04:30 UTC, davidli2010 requested changes

2023-08-06 04:30 UTC, davidli2010 commented on src/lib.rs
> +mod operators;
`mod operator`

2023-08-06 04:30 UTC, davidli2010 commented on src/operators/mod.rs
> +    fn derive_statistics(&self, _optimizer_ctx: &OptimizerContext, _input_stats: &[Rc<Statistics>]) -> Statistics;
Do we have to pass `OptimizerContext`, or only `MdAccessor`?

2023-08-07 15:16 UTC, LiBinfeng-01 approved these changes

2023-08-07 15:24 UTC, merged